var test = {
	question :[{
		id:"0",
		question:"...",
		answer_A:"...",
		answer_B:"...",
		answer_C:"...",
		answer_D:"..."，
		correct_answer:"1"//1-4代表A-D
	},{
		id:"1",
		question:"...",
		answer_A:"...",
		answer_B:"...",
		answer_C:"...",
		answer_D:"..."，
		correct_answer:"1"
	},{
		id:"2",
		question:"...",
		answer_A:"...",
		answer_B:"...",
		answer_C:"...",
		answer_D:"..."，
		correct_answer:"1"
	},{
		id:"3",
		question:"...",
		answer_A:"...",
		answer_B:"...",
		answer_C:"...",
		answer_D:"..."，
		correct_answer:"1"
	},{
		id:"4",
		question:"...",
		answer_A:"...",
		answer_B:"...",
		answer_C:"...",
		answer_D:"..."，
		correct_answer:"1"
	},{
		id:"5",
		question:"...",
		answer_A:"...",
		answer_B:"...",
		answer_C:"...",
		answer_D:"..."，
		correct_answer:"1"
	},{
		id:"6",
		question:"...",
		answer_A:"...",
		answer_B:"...",
		answer_C:"...",
		answer_D:"..."，
		correct_answer:"1"
	},{
		id:"7",
		question:"...",
		answer_A:"...",
		answer_B:"...",
		answer_C:"...",
		answer_D:"..."，
		correct_answer:"1"
	},{
		id:"8",
		question:"...",
		answer_A:"...",
		answer_B:"...",
		answer_C:"...",
		answer_D:"..."，
		correct_answer:"1"
	},{
		id:"9",
		question:"...",
		answer_A:"...",
		answer_B:"...",
		answer_C:"...",
		answer_D:"..."，
		correct_answer:"1"
	},{
		id:"10",
		question:"...",
		answer_A:"...",
		answer_B:"...",
		answer_C:"...",
		answer_D:"..."，
		correct_answer:"1"
	}]
}